### ISSUE TITLE
How to extend ogdf-python with own C++ class?

### ISSUE THREAD

**Issue by ghost** [ogdf/ogdf-python#1]
I want to extend OGDF with new classes. After generate documentation and set the environment variable in Jupyter Notebook 

```
%env OGDF_DOC_DIR=<dir>/ogdf/doc
```

I get the following error when trying to use the class `PlanarizerMixedInsertion`. 

```
AttributeError: <namespace cppyy.gbl.ogdf at 0x55c94935bfa0> has no attribute 'PlanarizerMixedInsertion'. Full details:
  type object 'ogdf' has no attribute 'PlanarizerMixedInsertion'
  ('ogdf::Module',)
  'PlanarizerMixedInsertion' is not a known C++ template
  'PlanarizerMixedInsertion' is not a known C++ enum
The name ogdf::PlanarizerMixedInsertion couldn't be found in the docs.
```

I think the error may be something went wrong while updating `doxygen.json` with `doxygen.py`.

Might you be so kind and make a tutorial on how users can use your library with a private extension of OGDF?

**Comment by ghost** [comment]
Problem solved. My mistake was to generate the documentation myself with `doxygen doc/ogdf-doxygen.cfg`. The doc documentation should be done with the Makefile target.

**Comment by N-Coder** [comment]
I need a little more information on what you exactly mean with "private extension". Did you just add further classes to the OGDF source tree and recompile the whole library? Then stuff should just work, as long as you `cppinclude` the corresponding headers you added first. Or did you create a new library that's compiled independently? Then you'd need to call `cppyy.load_library` with the resulting dynamic lib. See the `__init__.py` file of ogdf-python for the little stuff we do for loading the C++ library, the heavy lifting is then done by cppyy while we only add some "pythonizations" that add a little syntactic sugar. The whole docs/doxygen thing is only to copy the C++ docs to the python interface classes and to provide hints to a missing header when a cppinclude is missing, but both is entirely optional. You can comment out the calls to `pythonize_docstrings` and
`wrap_getattribute` in pythonize/`__init__.py` and the docs won't be touched. So I don't think the docs should affect the loading of classes in any way.

**Comment by ghost** [comment]
Apologies for the delayed response.

I have an example of my problem (and solution) in the following repo [OGDF clone](https://github.com/longpollehn/ogdf). 

As you can see in the commit diff, I added the new class `Example` in [src/ogdf/example/Example.cpp](https://github.com/longpollehn/ogdf/blob/master/src/ogdf/example/Example.cpp) and [include/ogdf/example/Example.h](https://github.com/longpollehn/ogdf/blob/master/include/ogdf/example/Example.h). 

After compiling the shared library, I try to use the class in Jupyter Notebook (as can be found in [Example without Doc.ipynb](https://github.com/longpollehn/ogdf/blob/master/Example%20without%20Doc.ipynb)). However, I get the complaint 

```
AttributeError: <namespace cppyy.gbl.ogdf at 0x56231ec73ee0> has no attribute 'Example'. Full details:
  type object 'ogdf' has no attribute 'Example'
  'ogdf::Example' is not a known C++ class
  'Example' is not a known C++ template
  'Example' is not a known C++ enum
The name ogdf::Example couldn't be found in the docs.
```

After generating the XML documentation with `make doc`  and setting the environment variable `OGDF_DOC_DIR`, the Jupyter Notebook works (as can be found in [Example with Doc.ipynb](https://github.com/longpollehn/ogdf/blob/master/Example%20with%20Doc.ipynb)). 

I hope to clarify some ambiguity.

**Comment by N-Coder** [comment]
This might be a compatibility issue with ogdf-python 0.1.3 and some more recent versions of cppyy. It should be fixed in ogdf-python 0.1.4 (released 8 days ago). Could you retry with that version?
